name: scm_vae
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.10.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=10.2
  - pytorch-lightning=1.7.6
  - imageio
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - notebook
  - ipywidgets
  - pip
  - pip:
    - gdown